### ISSUE TITLE
Clarify Coinbase transaction for pool integration.

### ISSUE THREAD

**Issue by Kukks** [straks/straks#5]
I am trying to implement Straks support in a mining pool called miningcore but am having trouble with treasury funding validation(`cb-no-treasury-funding`). The PR is here: https://github.com/coinfoundry/miningcore/pull/90 

This is an example transaction im generating for the coinbase transaction for testnet.
```
{{
  "hash": "558b561b21fba83fe7967420e2cc2d0778909b75d60f1c26e220fcb5248d9ba1",
  "ver": 1,
  "vin_sz": 0,
  "vout_sz": 2,
  "lock_time": 0,
  "size": 76,
  "in": [],
  "out": [
    {
      "value": "9.50000000",
      "scriptPubKey": "OP_DUP OP_HASH160 026d4467d3eaec9ca1c7ba9257ceb1bc4573e73d OP_EQUALVERIFY OP_CHECKSIG"
    },
    {
      "value": "0.50000000",
      "scriptPubKey": "OP_HASH160 737c37ce6ef1ea0ca88cb947ecb9aee189c6ba23 OP_EQUAL"
    }
  ]
}}
```

Any help would be great at this point as I'm at a loss. :)  I think it's in everyone's interests to offer an alternative mining pool implementation in case a bug crashes the only implementation around. :)

**Comment by ekamgit** [comment]
As you indicated the scriptPubKey you generate is incorrect. You are removing too many bytes from the beginning of the hash and leaving an extra pair at the end.

If you compare your hash to one from a valid testnet transaction, you will see where the issue lies.

```
737c37ce6ef1ea0ca88cb947ecb9aee189c6ba23
f9737c37ce6ef1ea0ca88cb947ecb9aee189c6ba
```
As shown above, the first hash is shifted to the left and is incorrect.

To get the correct hash you need to decode the address from base58 and then remove the first byte (version) and the last 4 bytes (checksum).
